export const lesson = {
  number: "7.1.2",
  title: "Obtain Project Stakeholder Approval of Project Completion",
  screens: [
    {
      id: "hook",
      tab: "The signature",
      type: "reveal",
      kicker: "Screen 1 — Hook",
      headline: "A courier dropping a package at your door and waving through the window isn't delivery.",
      lead: "They need an actual signature — from someone specifically authorized to give it — before the delivery officially counts and responsibility shifts to you.",
      heading: "A courier dropping a package at your door and waving through the window isn't delivery. They need an actual signature — from someone specifically authorized to give it — before the delivery officially counts and responsibility shifts to you.",
      cta: "Reveal the signature",
      image: "courier-signature",
      reveal: {
        title: "Approval is a specific, documented event",
        text: "Enabler 10.1 requires obtaining project stakeholder approval of project completion — and every word in that sentence is load-bearing. A project that feels finished, that everyone seems happy with, that's been running quietly in production for weeks — none of that is acceptance. Acceptance is a specific, documented event, and it either happened or it didn't.",
        image: "courier-signature",
      },
    },
    {
      id: "words",
      tab: "Three words",
      type: "accordion",
      kicker: "Screen 2 — Three Load-Bearing Words",
      headline: "Every one of these three words is doing real work.",
      heading: "Read the enabler's wording closely.",
      intro: "Every one of these three words is doing real work. Click each to explore.",
      image: "three-words",
      items: [
        { title: "OBTAIN", text: "The project manager actively secures it. Acceptance left to drift never arrives." },
        { title: "APPROVAL", text: "A decision by the accepting authority — the sponsor, customer, or product owner the charter names. The right signature from the wrong person binds nobody." },
        { title: "COMPLETION", text: "Judged against the criteria set earlier, not against satisfaction in the room. A project can feel done and still not meet its own exit criteria." },
      ],
    },
    {
      id: "mechanics",
      tab: "Four-step mechanics",
      type: "accordion",
      kicker: "Screen 3 — The Four-Step Mechanics",
      headline: "The mechanics are deliberately simple",
      heading: "The mechanics are deliberately simple — four steps that turn a feeling of “done” into an actual record. Click each to explore.",
      intro: "",
      image: "four-step-mechanics",
      items: [
        { title: "Validate Scope Did Most of the Work Already", text: "Deliverable-by-deliverable formal acceptance happens throughout monitoring and controlling, separate from the final closure of the whole project. A project that validated continuously arrives at final acceptance holding a folder of signed deliverables — the difference between a ceremony and a siege." },
        { title: "The Acceptance Review", text: "Walks the criteria checklist with the accepting authority, evidence sitting beside each item." },
        { title: "Three Lanes", text: "The decision lands in one of three places: accept; accept with conditions; or reject the gap back to rework." },
        { title: "The Acceptance Certificate", text: "Written, dated, referencing the criteria, signed by the chartered authority. This record authorizes everything downstream — transition, contract closure, financial closure, release." },
      ],
      quiz: {
        question: "Scenario: A project has been validating each deliverable formally throughout its execution, collecting signed acceptance for each one as it was completed. At final closure, the project manager presents this folder of signed deliverables to the accepting authority for the final acceptance review. What does this scenario best illustrate?",
        answers: [
          "An unnecessary duplication of effort, since deliverables were already accepted individually",
          "A violation of the charter, since only the sponsor should review deliverables",
          "A sign that the project skipped the acceptance review step entirely",
          "The intended relationship between Validate Scope and final closure — continuous deliverable-level acceptance means final acceptance confirms the whole meets exit criteria, rather than starting from scratch",
        ],
        correct: 3,
        correctFeedback: "Correct! This is exactly the intended design — deliverable-by-deliverable acceptance throughout the project (Validate Scope) means final closure confirms the whole project against exit criteria, rather than re-litigating every deliverable from zero. It's the difference between a ceremony and a siege.",
        incorrectFeedback: "Reconsider — this isn't duplication (the two acceptance events serve different purposes), it doesn't violate anything about who reviews deliverables, and the acceptance review is very much still happening here, just built on a strong foundation.",
      },
    },
    {
      id: "conditional",
      tab: "Conditional acceptance",
      type: "reveal",
      kicker: "Screen 4 — Conditional Acceptance: The Honest Middle Lane",
      headline: "Real projects rarely close at 100.000%.",
      heading: "Real projects rarely close at 100.000%. The professional question is what the missing fraction actually is.",
      cta: "Reveal the middle lane",
      image: "conditional-acceptance",
      reveal: {
        title: "Conditional Acceptance: The Honest Middle Lane",
        text: "Conditional acceptance handles minor open items — cosmetic defects, documentation polish, a non-blocking feature gap — by recording each on a punch list: written, owned, dated, tracked to closure after acceptance, often with a holdback or warranty mechanism where contracts are involved. Two disciplines keep it honest. First, the conditions must be genuinely minor — conditional acceptance that papers over an unmet exit criterion is not acceptance, it's a deferred dispute; material gaps go back to rework first. Second, the punch list must survive the project: items transfer to named owners, usually in operations, with dates — or they quietly become the next project's archaeology.",
        image: "conditional-acceptance",
      },
    },
    {
      id: "traps",
      tab: "Exam traps",
      type: "accordion",
      kicker: "Screen 5 — The Exam Traps: Variations of Informality",
      headline: "Something that feels like acceptance but isn't.",
      heading: "Every trap the exam sets here is the same shape: something that feels like acceptance but isn't. Click each to explore.",
      intro: "",
      image: "informality-traps",
      items: [
        { title: "“The Customer Has Used the System in Production for a Month”", text: "Usage is not acceptance. Get the signature." },
        { title: "“The Sponsor Emailed Thanks”", text: "Gratitude is not sign-off." },
        { title: "“Everyone Agreed in the Meeting”", text: "Minutes are not a certificate." },
        { title: "“The PM Accepted on the Sponsor's Behalf”", text: "The accepting authority is named in the charter, and it is never the person delivering the work." },
      ],
      quiz: {
        question: "Scenario: A project's deliverable has been running in the customer's production environment for six weeks without complaint. The project manager considers this sufficient evidence of acceptance and moves forward with closing the project, without obtaining a signed acceptance certificate from the accepting authority named in the charter. What is the issue with this approach?",
        answers: [
          "Usage is not acceptance — a signed certificate from the accepting authority named in the charter is still required, regardless of how smoothly the deliverable has been running",
          "The issue is only that six weeks isn't long enough; a longer production period would have been sufficient",
          "The issue is that production usage should have been documented in the meeting minutes instead",
          "There is no issue — six weeks of trouble-free production use is a reasonable substitute for formal acceptance",
        ],
        correct: 0,
        correctFeedback: "Correct! This is exactly the “usage is not acceptance” trap — no length of trouble-free production use substitutes for the actual signed record from the named accepting authority. The certificate is what authorizes everything downstream, not the absence of complaints.",
        incorrectFeedback: "Reconsider — no duration of usage converts into formal acceptance on its own, and meeting minutes wouldn't fix this either; the issue is the missing signed certificate from the named accepting authority, full stop.",
      },
    },
    {
      id: "exam",
      tab: "Exam lens",
      type: "reveal",
      kicker: "Screen 6 — Synthesis (Exam Lens)",
      headline: "A friendly wave through the window was never the delivery.",
      heading: "Back to that courier at the door one more time — because a friendly wave through the window was never the delivery. The signature was.",
      cta: "Reveal the exam lens",
      image: "exam-signature",
      reveal: {
        title: "Synthesis (Exam Lens)",
        text: "Obtaining stakeholder approval of project completion means actively securing (obtain) a decision from the accepting authority the charter names (approval), judged against exit criteria rather than room satisfaction (completion). Validate Scope does most of the work throughout the project; final acceptance confirms the whole against exit criteria; the decision lands in one of three lanes — accept, accept with conditions, or reject; and the acceptance certificate authorizes everything downstream. Conditional acceptance is the honest middle lane for genuinely minor items, tracked on a punch list that survives the project. And every exam trap here is the same shape: usage, gratitude, minutes, and a PM signing on someone else's behalf are all informality standing in for a record that was never actually made.",
        bullets: [
          "Three load-bearing words: obtain (actively secured), approval (by the charter-named authority), completion (against exit criteria)",
          "Four-step mechanics: Validate Scope's continuous acceptance, the acceptance review, three lanes (accept/conditional/reject), the acceptance certificate",
          "Conditional acceptance requires genuinely minor items on a tracked punch list with named owners — material gaps go back to rework",
          "Exam traps: usage ≠ acceptance, gratitude ≠ sign-off, minutes ≠ certificate, and only the charter-named authority can accept — never the PM on their behalf",
        ],
        image: "exam-signature",
      },
    },
  ],
};
